@startuml

actor user as "User"

rectangle Database

rectangle "World Fact Book" {
    usecase UC4 as "get countries by population"

    usecase UCa as "Print largest to smallest"

    user     - UC4
    UC4 ..> UCa : include
    UC4 - Database
}

@enduml